#!/usr/bin/python

"""Randomly set the wallpaper using wal"""
# To run in cron:
# echo $DISPLAY
# echo $DBUS_SESSION_BUS_ADDRESS
# */15 * * * * DISPLAY=<display> DBUS_SESSION_BUS_ADDRESS=<dbus> PATH="/usr/bin:/path/to/rwall" RWALL_WALLPAPERS="/path/to/wallpapers" rwall -p -rp -b -z -d
import os
import random
import subprocess
import sys
import argparse

from modules import Polybar, RofiPowermenu, Bspwm, Zed, Dunst

def get_current_wallpaper():
    """Get the path of the current wallpaper"""
    wal_wallpaper_path = os.path.expanduser("~/.cache/wal/wal")
    with open(wal_wallpaper_path, "r", encoding="utf-8") as wal_file:
        current = wal_file.read().strip()
        return os.path.basename(current)

def get_wallpaper_fullpath(wallpaper):
    """Get the fullpath of the given wallpaper"""
    return os.path.join(WALLPAPER_DIR, wallpaper)

def parse_args():
    parser = argparse.ArgumentParser(usage="RWALL_WALLPAPERS=\"/path/to/wallpapers\" rwall", description="Randomly set a wallpaper using wal")
    parser.add_argument("-p", "--polybar", action="store_true", help="Adds wal colours to an ini file stored in the polybar config directory")
    parser.add_argument("-rp", "--powermenu", action="store_true", help="Generate styles for Rofi Powermenu")
    parser.add_argument("-b", "--bspwm", action="store_true", help="Reload BSPWM after wallpaper has been set")
    parser.add_argument("-z", "--zed", action="store_true", help="Generate Zed theme")
    parser.add_argument("-d", "--dunst", action="store_true", help="Generate Dunst styles")
    return parser.parse_args()

CURRENT_WALLPAPER = get_current_wallpaper()
ARGS = parse_args()
SCRIPT_DIR = f"{os.path.dirname(os.path.realpath(__file__))}/scripts"
WALLPAPER_DIR = os.getenv("RWALL_WALLPAPERS")
MODULES = {
    "polybar": Polybar,
    "powermenu": RofiPowermenu,
    "bspwm": Bspwm,
    "zed": Zed,
    "dunst": Dunst
}

if WALLPAPER_DIR is None:
    print("rwall wallpaper directory not set")
    sys.exit(1)

artwork = [f for f in os.listdir(WALLPAPER_DIR) if os.path.isfile(os.path.join(WALLPAPER_DIR, f))]
try:
    artwork.remove(CURRENT_WALLPAPER)
except ValueError:
    pass

random_wallpaper = random.choice(artwork)
wallpaper_path = get_wallpaper_fullpath(random_wallpaper)

subprocess.run(["wal", "-i", wallpaper_path], check=True)

for arg, mod in MODULES.items():
    if getattr(ARGS, arg):
        mod(SCRIPT_DIR).run()

print(f"Wallpaper set to: {wallpaper_path}")
